### ISSUE TITLE
Missing Insecure flag for self signed cert ?

### ISSUE THREAD

**Issue by Zer0-Tolerance** [croservices/cro-http-test#10]
Hi Johnathan,

I can't seem to find a way to access https website using Cro::HTTP client , because it's complaining about the TLS verify that fails how can one disable this behavior ? I believe this is supported by IO::Socket::ASYNC::SSL so maybe I'm missing something ? 
Example error message: 
`Host XXX.XXX.XXX does not match any subject alt name on the certificate`
`Certificate contains no altnames to check host against`
`...`

**Comment by jnthn** [comment]
Please see [this recent documentation commit](https://github.com/croservices/cro/commit/73fd2832b177e4a3ca960fbb41ddfe6684dbf60e).

**Comment by Zer0-Tolerance** [comment]
thanks a lot it works with this :
`my $res=await Cro::HTTP::Client.get("https://8.8.8.8",ca => { :insecure })`
